### ISSUE TITLE
Workflow Runs generate Server Error

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-client#26]
Currently when running a workflow, even though a workflow has been validated as "valid", a 500 server error occurs.

**Comment by mrbannon** [comment]
Please give instructions on how to recreate this. It doesn't happen for me.

**Comment by musicus** [comment]
Two resources were specified. A N-Gram workflow was created, adding the NoteRest indexer on top with a red inlet, and a button outlet. Outlet was connected to inlet of the Vertical and Horizontal Indexer jobs respectively. The outlets of both the vertical and horizontal indexer jobs were connected to the two required inlets on the Ngram indexer. An outlet was added to Ngram indexer. All jobs were renamed. The workflow was validated, which did not generate a "success" or error message. The run was pushed, which directed me to the Workflow Run page, where I named and described the Workflow Run. The run button was pushed. The 500 server error displayed in my console.

**Comment by mrbannon** [comment]
Tx. I'll check it out Friday.

**Comment by mrbannon** [comment]
I wasn't able to recreate this. Hmm...

Gonna leave this open. If it happens again, please include details of the error. Tx.

**Comment by ahankinson** [comment]
@musicus can you post a json export of the workflow?

**Comment by ahankinson** [comment]
Are you running the server locally? You should see a log in the server console.

**Comment by musicus** [comment]
No. Not working on a local server. In either case both workflows ended up running successfully. One finished Friday, August 28th 2015, 7:40:53 pm, the other Friday, August 28th 2015, 11:31:00 pm. However, that means that both of workflows took more than 6 hours to finish.

**Comment by mrbannon** [comment]
I think those were probably runs I started. :)

**Comment by mrbannon** [comment]
Stale...can't recreate.
